#!/usr/bin/env node
/* eslint-disable */
// AUTO-GENERATED SCRIPT: Converts config.json to a TypeScript definition.
// Usage: node scripts/convert-config.js

const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const configPath = path.join(projectRoot, 'config.json');
const libDir = path.join(projectRoot, 'src', 'lib');
const runtimePath = path.join(libDir, 'runtime.ts');

if (fs.existsSync(runtimePath)) {
  fs.unlinkSync(runtimePath);
  console.log('Deleted old runtime.ts');
}

let rawConfig;
try {
  rawConfig = fs.readFileSync(configPath, 'utf8');
} catch (err) {
  console.error(`Failed to read ${configPath}:`, err);
  process.exit(1);
}

let config;
try {
  config = JSON.parse(rawConfig);
} catch (err) {
  console.error('config.json is not valid JSON:', err);
  process.exit(1);
}

const tsContent =
  `// This file is generated by scripts/convert-config.js. Do not edit it manually.\n` +
  `/* eslint-disable */\n\n` +
  `export const config = ${JSON.stringify(config, null, 2)} as const;\n\n` +
  `export type RuntimeConfig = typeof config;\n\n` +
  `export default config;\n`;

if (!fs.existsSync(libDir)) {
  fs.mkdirSync(libDir, { recursive: true });
}

try {
  fs.writeFileSync(runtimePath, tsContent, 'utf8');
  console.log('Generated src/lib/runtime.ts');
} catch (err) {
  console.error('Failed to write runtime.ts:', err);
  process.exit(1);
}
